version: 2.1

orbs:
  node: circleci/node@4.1
  composer: stockfiller/composer@1.0.0

jobs:
  lint:
    docker:
      - image: cimg/php:7.4.5-node
    steps:
      - checkout
      - composer/install
      - node/install-packages
      - run: npm run lint

workflows:
  lint-flow:
    jobs:
      - lint
