version: 2.1

orbs:
  node: circleci/node@5.0.0
  php: circleci/php@1.1.0

jobs:
  lint:
    docker:
      - image: cimg/php:7.4.5-node
    steps:
      - checkout
      - node/install
      - node/install-packages
      - php/install-packages
      - run: npm run lint

workflows:
  lint-flow:
    jobs:
      - lint
      - node/test:
          run-command: test:js
